package version

// DO NOT EDIT!
// file generated by scripts/generate-version-info.sh

const (
	commit_date int64 = 1685055399
	revision          = "7de979a12688626a3c687cc4742e8f505be4bb26"
	branch            = "main"
	version           = "0.0.2"
	last_tag          = "0.0.2"
)
