package version

// DO NOT EDIT!
// file generated by scripts/generate-version-info.sh

const (
	commit_date int64 = 1685063917
	revision          = "11b604d9b61e098485a1cd657a21e38f295fa520"
	branch            = "sqmain"
	version           = ""
	last_tag          = ""
)
