package version

// DO NOT EDIT!
// file generated by scripts/generate-version-info.sh

const (
	commit_date int64 = 1684981072
	revision          = "31d4e35e6265e1c30bb2fca55060af8422ae88a0"
	branch            = "main"
	version           = ""
	last_tag          = "0.0.1-1-g31d4e35"
)
